[build.environment]
  # Makes Netlify fetch real Git LFS blobs instead of pointer files
  GIT_LFS_ENABLED = "true"

# Correct MIME + long-lived caching for video assets
[[headers]]
  for = "/assets/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*.webm"
  [headers.values]
    Content-Type = "video/webm"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
